### ISSUE TITLE
WebAssembly, Scheduler component, drag to resize event not working

### ISSUE THREAD

**Issue by Ronzan** [DevExpress/Blazor#112]
Using the Scheduler component in a WebAssembly project, it is not possible to resize an event because the mouse cursor is "flickering" between the resize cursor and the select cursor (if this doesn't make sense I can create video/gif).

- It happens in both dayview and weekview, didn't try month view.
- I used a standard Blazor WebAssembly projects, .NET core hosting and PWA.
- I used the sample code from demo site.
- Tried with both preview2 and preview3 of Blazor WebAssembly.
- Tested with Chrome and Edge (chromium), latest versions.
- Using DevExpress.Blazor 16.2.4
- Drag to move events around works fine.
- It works as expected if I create a Blazer Server-side project.

**Comment by zabelin-vladimir** [comment]
Hello @Ronzan 

Thank you for your description. I reproduced this behavior. We will research it in the context of the [Scheduler for Blazor WebAssembly - It's not possible to resize an appointment due to the cursor's incorrect behavior](https://supportcenter.devexpress.com/ticket/details/t877559/scheduler-for-blazor-webassembly-it-s-not-possible-to-resize-an-appointment-due-to-the) ticket.
