### ISSUE TITLE
Blazor Navbar - Drawer control

### ISSUE THREAD

**Issue by BlagoCuljak** [DevExpress/Blazor#12]
Hello, I'm working on my first Blazor project, and should be done by the time Blazor and Core 3.0 hits RTM (September).

However, I'm having issues with the vertical menu, tried to implement submenu, but it just doesn't work. Example is found here:
https://www.codeply.com/go/q0b6ILuRyx/bootstrap-4-vertical-menu-with-submenu

Da you plan to to have control similar to Drawer, or something we can use instead default NabBar?

**Comment by SergeySeleznyov** [comment]
Hi @BlagoCuljak ,

Thank you for your suggestion!

According to our [Roadmap](https://community.devexpress.com/blogs/aspnet/archive/2019/06/24/blazor-roadmap-what-you-can-expect-in-the-next-few-months-from-devexpress.aspx) we are currently working on the Tree View component, which looks like as follows:

![image](https://user-images.githubusercontent.com/950357/60081881-5d8e9200-973b-11e9-9f8f-ddcea176a9ca.png)

Also, we will use it in our demo navigation instead of the current menu in the left panel.
It is going to be delivered within several days.

How do you think, having Tree View component and using Bootstrap-based approaches for panel (like it is done in Blazor template) will you be able to implement UI you like?

**Comment by BlagoCuljak** [comment]
Well that would be ideal. Also, adding icons is a must in those situations.

**Comment by SergeySeleznyov** [comment]
Great to hear that!
 
The Tree View node has the **IconCssClass** property, which allows you to set an icon for this node.
 
Thank you for your feedback!

**Comment by SergeySeleznyov** [comment]
Hi @BlagoCuljak ,
 
We have just updated the demos and components (NuGet package).
The Tree View component is in the new version.
The Tree View component is used for the demo navigation, so you can take an example from the demo source.

**Comment by SergeySeleznyov** [comment]
Hi @BlagoCuljak ,
 
I hope with new features you can now achieve your goal in your project.
I'm closing this issue. Please feel free to reopen it (or create a new one) should you have any difficulty.

**Comment by BlagoCuljak** [comment]
Hi @SergeySeleznyov ,
Last week, I was on vacation, and didn't had time to respond. Great, looking forward to update my project. Have good one.

**Comment by SergeySeleznyov** [comment]
Hi @BlagoCuljak ,

Thank you for the update!
It would be great if you keep us posted of your results.
 
Thank you very much for your time.
