### ISSUE TITLE
Are the components Mobile ready/responsive?

### ISSUE THREAD

**Issue by BenHayat** [DevExpress/Blazor#14]
Hello Team;

I was examining something very interesting this weekend and then this question came up.
When I test the online demo, in Chrome and set it into mobile mode and then run the demo, it seems like, some of the components don't respond to screen size changes, i.e. grid.

My question is, for V1, will the components be responsive out of the box?

Thank you in advance!

**Comment by SergeySeleznyov** [comment]
Hello @BenHayat ,
 
Our component were created based on the Bootstrap framework. As a result, the grid resizes according to screen width.
At the moment, Blazor does not provide a way to change component layout according to screen width, like in [our ASP.NET controls](https://demos.devexpress.com/aspxgridviewdemos/Adaptivity/AdaptiveLayout.aspx?device=tablet&rotate=0).
 
While adaptive layout is not in the Blazor Roadmap for V1, we will definitely provide it in the future.
In the meantime, you can use CSS with media rules to show/hide grid columns or re-layout your Grid Edit Form templates.

**Comment by BenHayat** [comment]
Thanks Sergey;
As long as progress is made in this area, I'm happy, since Mobile-first is becoming # 1 priority.

We had been doing some prototyping with MVC Core and since each page/view in MVC is going to transfer all the HTML/CSS/JS to the client, the performance test was very poor on Mobile's bandwidth, especially when users are used seeing their daily apps goes from one page to another in a snap.

Doing test even on the server-side of Blazor and watching the network, after the initial page load, all other pages have little amount of load. So Blazor seems to be a better choice.
However, an important question has come up. Let's say if I have 100 or even 1000 pages in MVC project, those numbers do not affect on each page load time. They are server as demanded.
My question is, if I create a server-side Blazor app with 100 pages in it, when a user starts the app, Are ALL the 100 pages going to get transferred from server to client? Just like a SPA app does? This is a problem we ran into with Vue app. If you have a lot of pages in Vue, you have to use Lazy Loading to sort of break up the download process.
Have you guys tested something like a test with many pages to see How Blazor works?

I'd appreciate any feedback in this area.
Thanks!

**Comment by SergeySeleznyov** [comment]
You are always welcome Ben,
 
> Are ALL the 100 pages going to get transferred from server to client

Blazor uses the "Virtual DOM" technique. It means that Blazor keeps the page DOM in the server, tracks this DOM's modification during operations, and sends only the changes to the customer.
As a result, you can do the following experiment:
1. Open some demo, let's say "https://demos.devexpress.com/blazor/GridColumnTypes"
2. In Chrome developer tools find the TR node inside the Grid:

```
<td>....Cold....
```

3. In Chrome developer tools add some attribute, let's say, data-test="MyTest"

```
<td data-test="MyTest">...Cold...
```

4. Now switch the grid's page - all the grid rows data are changed, right?
5. Let's find the TR node on the same position:

```
<td data-test="MyTest">....Warm....
```
 
Data has been changed, but your attribute remains!
Server code did nothing with the attribute, so the attribute wasn't in the server-side Virtual DOM change that has been sent from the server.
 
Now, apply the same logic from Grid pages navigation to the whole App navigation.
When you click a navigation link, the server applies some change to the server-side DOM (it keeps a server-side equivalent of your client page).
Blazor tracks what has been changed on the page when you navigate it and sends the difference to the client (the difference between what was in your browser before a navigation link click and after that).
 
So, you can repeat the experiment with the data-test attribute with some HTML node that does not visually change during navigation - sole navigation Tree View node for instance - your data-test attribute will persist.
 
So, technically not the "page" gets transferred from the server to the client, but only the difference between when you navigate and after that.
 
> if I create a server-side Blazor app with 100 pages in it, when a user starts the app, Are ALL the 100 pages going to get transferred from server to client? Just like a SPA app does?
Since Blazor is a server SPA, all pages are in the place where they work - on the server.
When you operate with the App, the DOM difference gets transferred to the client.
 
> Have you guys tested something like a test with many pages to see How Blazor works?
I have just made some experiment:
1. Take our demo sources
2. In Visual Studio, CTRL+C some complex page
3. CTRL+V it many times.
4. Launch the demo - there is not performance degradation
 
You can repeat it on your side (it fast enough).
 
I found it useful to think about server-side Blazor like about a Remote Desktop. Where a user's mouse/keyboard operation goes to the server and the server responces with HTML differences (instead of "pixels" in the case of real Remote Desktop).
Like with Remote Desktop, with a server-side Blazor client, the device shouldn't be as powerful as the server, because all the soft operates on the server side, while the client sees only html (like "pixels" in the case of Remote Desktop).
 
I hope this helps.
 
Thank you for your interest in our product!

**Comment by BenHayat** [comment]
Awesome explanation.
I did NOT know Blazor Server-Side does the "DOM -Diff" on the server side and knows what to send back for the next changes. Pretty clever. Thank you for clearing this up.

So far, server-side solves a few problems:
1) Unlike client-side, our code stays on the server side.
2) Unlike client-side like Vue or Angular, that all the codes for the SPA must be loaded to client first, with server side we don't need to do that.
3) Unlike client-side, the app doesn't require a separate Web API to send data and doesn't require the complex auth system and sending tokens and using outside authentication server.
The only cons part on server-side is, if you got a 1,000 users, there is going to be 1,000 instances of the app running on the server and 1,000 SingalR connection.

But, we will see what MSFT does for client-side by Nov. 2020.

Much appreciate your answers, I'm sure others will benefit from your answer.
Thank you my friend!

**Comment by SergeySeleznyov** [comment]
Ben,
 
Thank you for your warm words. I'm very happy to help.

**Comment by Sm1le291** [comment]
Hi everyone! Can I use bootstrap layout for rows and cols as it follows from fact that  components use Bootstrap itself. Do I need to add bootstrap styles explicitly or if I add one visible control all css will be included automatically?
