### ISSUE TITLE
DxReportDesigner with ObjectDataSource problem

### ISSUE THREAD

**Issue by olowk** [DevExpress/Blazor#146]
Hello,

At the moment I can't seem to get the report designer to work with the objectdatasource. Am I doing something wrong? I can see the datasource in the report designer and also drag the column 'Name' onto the detail section of the report. But when I go to preview it shows nothing. I've noticed that all the demos are with the sqldatasource, is this mandatory for the blazor report designer?

PS: I know that there are extra spaces before the tagnames in the razor section of my code below but github doesn't want to show the razor code if a < is directly followed by text

`< DxReportDesigner Height="1000px" Width="100%" DataSources="@myDataSources">
  < DxReportDesignerWizardSettings UseFullscreenWizard="false"/>
< /DxReportDesigner>

@code {
  Dictionary<string, object> myDataSources = new Dictionary<string, object>();

  public class TestProduct
  {
    public string Name {get;set;} = "Name";
  }

  protected override void OnInitialized()
  {
    var ds = new DevExpress.DataAccess.ObjectBinding.ObjectDataSource();

    ds.DataSource = new List<TestProduct> { new TestProduct(), new TestProduct() };
    ds.Fill();
    myDataSources.Add("Data", ds);
  }
}`

**Comment by vasyaste** [comment]
Hello @olowk,

This issue is caused by the fact that the Web Report Designer receives a serialized copy of the report/datasource. This is required as our Web Report Designer operates with these objects on the client side by using JavaScript code. As you assign non-serializable collection to a DataSource property of your ObjectDataSource this collection cannot be serialized and data is lost.

In order to avoid this issue connect your ObjectDataSource to a helper method that returns the desired connection. The method name will be serialized with the data source, so data source will be able to get collection by calling the method.

For example, use the following code for the helper class:

```cs
public class MyHelper {
    public static IList<TestProduct> GetProducts() {
        // Return collection here
        ...
    }        
}
```

And this is how your data source should be connected to this method:

```cs
ObjectDataSource ods = new ObjectDataSource();
ods.DataSource = typeof(MyHelper); //Class name
ods.DataMember = "GetProducts"; //Method name
ods.Parameters.Clear(); //We use parameterless method
ods.Constructor = null; //A static method is used, so no constructor is needed
ods.RebuildResultSchema(); //Build schema
```

***P.S.** We kindly ask you to post further issues related to our **Web Reporting** products to our [Support Center](https://supportcenter.devexpress.com/ask) web portal. This will help us to process issues more efficiently. We greatly appreciate your understanding.*
