### ISSUE TITLE
TagBox controls with multiple columns double scrollbar

### ISSUE THREAD

**Issue by drinkwater99** [DevExpress/Blazor#168]
If I run the TagBox demo https://demos.devexpress.com/blazor/TagBox#MultipleColumns there are two vertical scrollbars which appear in the dropdown. Is there any way to prevent the extraneous scrollbar ?

**Comment by zabelin-vladimir** [comment]
Hello @drinkwater99 

I see only one scrollbar:
![image](https://user-images.githubusercontent.com/42369178/92082955-f1430000-edcd-11ea-890e-4528a5daf049.png)
Would you please specify the browser where this behavior occurred? Did you set any specific zoom level? Also please, share a screenshot of this issue.

**Comment by drinkwater99** [comment]
![image](https://user-images.githubusercontent.com/9962405/92179717-40f7ea80-ee13-11ea-8f3f-71e3ae4f1b71.png)

Occurs with Chrome :
Version 85.0.4183.83 (Official Build) (64-bit)

Not using any level (so 100%)

**Comment by b1tzer0** [comment]
Using Microsoft Edge (Chromium)
v 86.0.622.3 (Official build) dev (64-bit)

[cid:image001.png@01D6828E.34BDF700]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by zabelin-vladimir** [comment]
Hello @drinkwater99 

We reproduced this issue if the zoom level is not 100%. May be in your scenario you have the Window zoom? Our components support only 100% zoom level due to specifics of different browsers. However, we found that this specific case can be resolved at the level of our components. We are working on this issue in the context of the following thread: [TagBox for Blazor - The second scrollbar appears inside the item list if several columns are shown and browser zoom is not 100%](https://supportcenter.devexpress.com/ticket/details/t928848/tagbox-for-blazor-the-second-scrollbar-appears-inside-the-item-list-if-several-columns).

**Comment by drinkwater99** [comment]
My zoom level is at 100% so I don't think it's related to that (at least in my case).

**Comment by zabelin-vladimir** [comment]
Hello,

We have resolved this issue in the context of the [mentioned ticket](https://supportcenter.devexpress.com/ticket/details/t928848/tagbox-for-blazor-the-second-scrollbar-appears-inside-the-item-list-if-several-columns). Our demos were updated. So, I recommend you review the following demo: [TagBox - Multiple Columns](https://demos.devexpress.com/blazor/TagBox#MultipleColumns).

P.S. We are going to address technical requests only in our Support Center. If you have additional questions regarding this issue, feel free to contact us in our [Support Center](https://www.devexpress.com/ask).
