### ISSUE TITLE
Question on Menu

### ISSUE THREAD

**Issue by BenHayat** [DevExpress/Blazor#20]
Hello Team;

According to the blog, for V1 we should get a toolbar and popup menu.
Q1: Is the popup menu, the same as "Context Menu", where a user presses right mouse and get a popup menu related to that component?

Q2: What components can we put in the toolbar component? Also, can we place the toolbar on the left and right? If yes, can user hide/show the toolbar?
Suppose we put TreeView (as menu) in the toolbar, when user needs it, they can show it or they can hide it to give them more screen real estate for content.

Q3: when do you expect that we will get a regular menu system with sub menu, icons and etc?
It would be great to have data binding like TreeView, so we can create menu items at runtime. 
For example if the user is Admin, we can create a menu based on his role in database, which will render at runtime.

Thanks!
..Ben

**Comment by akorenchikov** [comment]
Hello Ben,
 
>Q1: Is the popup menu, the same as "Context Menu", where a user presses right mouse and get a popup menu related to that component?


Yes, you are right. The popup menu control will provide a functionality to implement a context menu (a similar functionality is demonstrated in [the demo](https://demos.devexpress.com/Bootstrap/Navigation/Menu.aspx#PopupMenu)).
  
>Q2: What components can we put in the toolbar component? Also, can we place the toolbar on the left and right? If yes, can user hide/show the toolbar?
Suppose we put TreeView (as menu) in the toolbar, when user needs it, they can show it or they can hide it to give them more screen real estate for content.


The behavior you described looks like the functionality the Drawer component supports. It is not in our roadmap, but the same functionality can be achieved with the help of bootstrap like it was done in the MS Blazor application template. The same is done with the Tree View component in our demo.
A toolbar is a set of some items/buttons with text/icons that you can click to perform a certain operation (this functionality is demonstrated in [the demo](https://demos.devexpress.com/Bootstrap/Navigation/Toolbar.aspx#AdaptivitySettings)).
Items will also provide the capability to display their own submenu with subitems or submenu template content. 
It is not supposed to put a tree view inside the toolbar. If you have scenarios when it is needed, please share them with us. We will take them into account.
 

>Q3: when do you expect that we will get a regular menu system with sub menu, icons and etc?
It would be great to have data binding like TreeView, so we can create menu items at runtime.
For example if the user is Admin, we can create a menu based on his role in database, which will render at runtime.


We want our first release set of components to be valuable and helpful, and thus we put components like Scheduler, but not a regular menu.
Unlike Scheduler, the regular menu can be implemented based on bootstrap, so we do not put it in our first release roadmap.
We put the popupmenu and toolbar just because they are required for our other component from the roadmap (Sheduler).
However the regular menu is a must-have, so there is no doubt that it will be implemented too.

Thank you for your attention to our products.

**Comment by BenHayat** [comment]
@akorenchikov ;
Thank you for your response; All the answers are clear and make sense. And I agree with them.
But it's always good to ask and get feedback and direction.
Thanks again!
