### ISSUE TITLE
Virtual Scrolling issues

### ISSUE THREAD

**Issue by rysep2** [DevExpress/Blazor#28]
I added the virtual scrolling attribute to my DevExpress grid. The grid now only shows ten rows and ist not scrollable. If a text is too long, it is cut and there is no way to read the full text.
I'm using server-side Blazor and my grid data source is a huge list of objects. What am I doing wrong?

```
                <DxDataGrid Data=@MyModel.Tracks
                            DataNavigationMode="@DataGridNavigationMode.VirtualScrolling"
                            SelectedDataRowChanged=@OnGridSelectionChanged>
                    <DxDataGridColumn Field=@nameof(Title.Type) Caption="Type"></DxDataGridColumn>
                    <DxDataGridColumn Field=@nameof(Title.Name) Caption="Name"></DxDataGridColumn>
                    <DxDataGridColumn Field=@nameof(Title.Artist) Caption="Artist"></DxDataGridColumn>
                </DxDataGrid>
```

**Comment by outsidergiant** [comment]
Hi,
 
Virtual Scrolling is intended to load small portions of records on a vertical scroll. It is useful when you need to render grid rows on demand.
If you wish to scroll horizontally, this feature will be delivered shortly. We are already working on this mode right now.
If you are experiencing any issues with Virtual Scrolling or face any other difficulties, please let me know. It will be also helpful if you provide me with some screenshots or code snippets with test data so that I can reproduce the problematic behavior on my side and come up with a better suggestion.

**Comment by rysep2** [comment]
The vertical scrolling is exactly what I want but the grid is somehow not scrollable. The grid only shows the first ten entries. If I sort by a specific column the entries change but still only the first ten are shown.

I replicated the issue in a simple project:
[VirtualScrollingExample.zip](https://github.com/DevExpress/Blazor/files/3411067/VirtualScrollingExample.zip)

**Comment by outsidergiant** [comment]
Thank you for providing your project. I see that our files from the [client-runtime directory](https://github.com/DevExpress/Blazor/tree/master/client-runtime), step #4 of the [How to create a new project](https://github.com/DevExpress/Blazor#how-to-create-a-new-project) paragraph, are not added to your project. Including them into the _Host.cshtml file will resolve the issue.
![VirtualScrolling](https://user-images.githubusercontent.com/17219648/61536995-a84fb100-aa3e-11e9-8760-bb3f6f21f061.png)
