### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by CCACX** [DevExpress/Blazor#31]
Hello,
i want to change the default language from english to german. 
Does someone know how to change it?

**Comment by outsidergiant** [comment]
Hi,

Our components are native so since .NET Core 3.0 doesn't support localization, they cannot be localized either. ASP.NET Core team has plans on this feature. See the [Blazor Roadmap Backlog](https://github.com/aspnet/AspNetCore/issues/8177).

**Comment by outsidergiant** [comment]
Hi,

I'm happy to inform you that we introduced Localization Support in v19.2. See our [Blazor Components - Localization, Asynchronous data operations, and more (v19.2.0)][0] blog post and the [How to localize DevExpress Blazor components][1] example.


[0]: https://community.devexpress.com/blogs/aspnet/archive/2020/01/17/blazor-components-localization-asynchronous-data-operations-and-more-v19-2-0.aspx
[1]: https://supportcenter.devexpress.com/internal/ticket/details/T850867

**Comment by imtrobin** [comment]
Hi, I don't use the resource for localization, is it able to specify a string like Caption so I can pass in my own localization?

**Comment by zabelin-vladimir** [comment]
Hello @imtrobin

Your scenario is not completely clear to me. As far as I understand, you can set some custom string based on the current culture to the "Caption" of the specific column of DxDataGrid. You can use the [Caption ](https://docs.devexpress.com/Blazor/DevExpress.Blazor.DxDataGridColumn.Caption)property to do that. However, our grid contains several UI elements with texts which cannot be customized by properties, for example, the text of the command button or the text in the group panel. Because of that, we recommend using our [Localization](https://docs.devexpress.com/Blazor/401564/common-concepts/localization) approach.

Best regards

**Comment by imtrobin** [comment]
Yes, that's what I meant, to customize the UI elements like New, Delete etc. Not using your localization method

**Comment by zabelin-vladimir** [comment]
Hello @imtrobin 

As I mentioned, DxDataGrid doesn't have the corresponding property to change the text in the mentioned UI elements. So, the only way to localize them is to use our localization mechanism.
