### ISSUE TITLE
Grid jumps in virtual scrolling mode

### ISSUE THREAD

**Issue by rysep2** [DevExpress/Blazor#55]
When I use the DxDataGrid in virtual scrolling mode, the grid sometimes scrolls (more like jumps) up/down without me doing anything. You can test it with the solution I uploaded if you slowly scroll down step by step. It works fine for the first about 30 entries but then it jumps around randomly.

[DevExVirtualScrolling.zip](https://github.com/DevExpress/Blazor/files/3725055/DevExVirtualScrolling.zip)

**Comment by SergeySeleznyov** [comment]
Hi @rysep2,

Thank you for informing us of this issue.
I tried to reproduce the issue on my side. Attached is a screencast illustrating my attempt.

![ezgif-6-dde48c6dc9cf](https://user-images.githubusercontent.com/950357/66826907-41b33400-ef56-11e9-8887-df01163a9e17.gif)

Would you please check whether this issue is the same as you describe?

**Comment by rysep2** [comment]
Hi @SergeySeleznyov 

Yes, that's what I meant.

**Comment by SergeySeleznyov** [comment]
Hi @rysep2,

Happy to inform you that this issue is fixed in version 19.2.1-beta.
Please feel free to reopen this issue should you have any difficulty.
