### ISSUE TITLE
Is it possible to override the pop-up and its fields of DxScheduler?

### ISSUE THREAD

**Issue by jhunexjun** [DevExpress/Blazor#61]
I'm relatively new to Blazor but what I want is to use the UI of the DxScheduler except the pop-up and some labels in the pop-up. Is it possible?

**Comment by outsidergiant** [comment]
Hi,

From what I gather, you wish to specify a custom appointment edit form and the capability to work with custom fields, right? If so, currently Scheduler doesn't provide this capability. These features are in our backlog, so it will be helpful if you share your use-case with us.

As for your question about labels, please try the solution from the [Is it possible to customize labels, appointments and the resource grouping of the scheduler](https://github.com/DevExpress/Blazor/issues/38) thread.

**Comment by cubed-it** [comment]
Is anything planned in this regard? We can't use the scheduler in its current form, because we cannot disable, replace or redirect the popup.
Would it be possible to create a read only scheduler?
As a demo the component is quite nice, but I do not see any way to use it for somethin productive....

**Comment by outsidergiant** [comment]
Hello @cubed-it ,

Currently, Scheduler doesn't provide an API to switch it to read-only mode. As a temporary workaround, you can use [DevExtreme Scheduler](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/SimpleArray/jQuery/Light/) which has the [disabled](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/#disabled) option. 

Refer to the following article describing how to add DevExtreme widgets in Blazor applications:
[How to use DevExtreme widgets in Blazor applications](https://supportcenter.devexpress.com/ticket/details/t886810/how-to-use-devextreme-widgets-in-blazor-applications)

**Comment by TheHokieCoder** [comment]
I'd like to +1 previous comments about how the Scheduler widget for Blazor applications is not very useful in production scenarios due to its lack of customization. I'd also like to re-iterate @cubed-it's question about the planning/timeline for adding features to the Scheduler Blazor component? You say it is a temporary workaround, but we'd like to know how temporary?

Our use case is two-fold:
1. We have events that have properties that do not match to a traditional calendar appointment. As an example, we load out equipment for each event, so the appointment object would need to be able to specify which equipment is loaned for that specific event. We would need to be able to add a control of our choosing to the create & edit forms so that the equipment could be listed.

2. In another scenario, we have appointments for advisors meeting with their students. As part of the appointment details, we need to customize the popup and edit forms such that we can display custom information about the student who is scheduled for that appointment. The appointment also correlates with information in other systems, so we need to be able to control how we can display that information and link to it, if necessary.

Any information you could provide for us would be greatly appreciated! Thanks!

**Comment by jhunexjun** [comment]
Additional info:

I have not been updated about this anymore but so far the best thing I could think of which was working on other framework is to use a pop-up of another customized dialog box and all the way disregard the  default one. So from there you can put as much textboxes, labels, buttons, etc. as you can. Hope that helps.

**Comment by TheHokieCoder** [comment]
@jhunexjun Thanks for that suggestion. We have a pretty good amount of experience with the DevExtreme controls, so we are going to go that route so that we still stay in the DevExpress ecosystem. We're just hoping to find out how long of a wait it'll be before the Scheduler widget will become fully featured via Blazor.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
