### ISSUE TITLE
Material design theme

### ISSUE THREAD

**Issue by drinkwater99** [DevExpress/Blazor#66]
Are there any plans to have a Material Design theme ?

**Comment by SergeySeleznyov** [comment]
Hi Angelo,

Material is one of the essential trends in modern design; we will definitely support it in the future. But currently, our components are missing several 'must-have' features required for many lines of business projects.
Thus, our immediate goal is to allow customers to build prototypes and then working applications. After that, we will focus on material design that is already implemented in our ASP.NET and DevExtreme components.

We would appreciate it if you specify the elements of the material design that you require for your current application. There is a chance that we will implement them earlier than we support material design in our Blazor components.

**Comment by BlagoCuljak** [comment]
Hi there Blazor fans!
There's a great library called matblazor, and looks amazing. Don't know if something like this will be in DX suite, but damn, if we could have a label/placeholder on that Textbox, that would be good addition.

https://www.matblazor.com

**Comment by dlmac** [comment]
It has been nearly a year on this topic. Any updates on the plan to allow Material Design?

**Comment by zabelin-vladimir** [comment]
Hello @dlmac

We are not planning to implement the specific theme with the Material design or any specific modes for our components in the next major release. At present, we focused our resources on DxDataGrid and editors. We are currently working on the features from our roadmap - [Blazor - Roadmap 2020 (Mid-Year Update)](https://community.devexpress.com/blogs/aspnet/archive/2020/07/09/blazor-roadmap-2020-mid-year-update.aspx).

Since our controls support different Bootstrap Themes, you can check if some of them meet your requirements. For example, check the [Materia theme](https://bootswatch.com/materia/), which you can review in [our demos](https://demos.devexpress.com/Blazor/GridColumnTypes).

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
