### ISSUE TITLE
NavMenu.razor always executed twice when init/refresh the app

### ISSUE THREAD

**Issue by goldmannyc** [DevExpress/Blazor#77]
From time to time noticed the flicking of navmenu probably because of it.

**Comment by zabelin-vladimir** [comment]
Hello @goldmannyc,

As far as I understand, you placed a breakpoint to the code of the *NavMenu.razor* component and it raised twice while loading of the application. It's expected behavior if the *ServerPrerendered* render mode is used to render the application component:

`<app>@(await Html.RenderComponentAsync<App>(RenderMode.ServerPrerendered))</app>`

When RenderMode is *ServerPrerendered*, the component is initially rendered statically as part of the page. Once the browser establishes a connection back to the server, the component is rendered again, and the component is now interactive.
Please check [this documentation article](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1#stateful-reconnection-after-prerendering) to learn more about this behavior.

> From time to time noticed the flicking of navmenu probably because of it.

I'm not sure about this issue. Did you reproduce it with our demos, or maybe you created a project with our components and it works incorrectly?
