### ISSUE TITLE
When HorizontalScrollBar is enabled the clear filter button breaks.

### ISSUE THREAD

**Issue by fotini15** [DevExpress/Blazor#84]
When I enable the Horizontal Scrollbar - the filter clear button CSS breaks.

    <DxDataGrid Data="@" ShowFilterRow="true" HorizontalScrollBarMode="@ScrollBarMode.Hidden"  >

![horzscroll-hidden](https://user-images.githubusercontent.com/59594464/71873051-efa33880-3169-11ea-8db7-0f168302e01c.png)

    <DxDataGrid Data="@" ShowFilterRow="true" HorizontalScrollBarMode="@ScrollBarMode.Visible"  >

![horzscroll-visable](https://user-images.githubusercontent.com/59594464/71873120-20836d80-316a-11ea-8b92-12ae361dd8e4.png)

**Comment by outsidergiant** [comment]
Hi,

Thank you for drawing our attention to this. This behavior is incorrect and I created the [DataGrid for Blazor - The clear button for the filter row editors is shown at an incorrect position if the horizontal scrollbar is shown](https://www.devexpress.com/Support/Center/Question/Details/T850224/datagrid-for-blazor-the-clear-button-for-the-filter-row-editors-is-shown-at-an-incorrect) report regarding this. We will update it and inform you once we have any news.

**Comment by outsidergiant** [comment]
Hello @fotini15,

We have fixed this issue issue. The fix is provided in v19.2.1 Beta. Please note, v19.2.1 Beta includes [breaking changes](https://supportcenter.devexpress.com/versionhistory?platformsWithProducts=3c616c71-03dc-46b9-a54f-1334a22dffe7&entries=BreakingChanges&startBuildName=19.2.1&endBuildName=19.2.1&buildsMode=Single&hasPlatformsWithProducts=true) that may affect your application. Feel free to use the previous version should you need a stable version for production purposes.

**Comment by fotini15** [comment]
Thanks @outsidergiant
