### ISSUE TITLE
MultipleSelectedDataRowsChanged called multiple times per click and with too many elements.

### ISSUE THREAD

**Issue by rysep2** [DevExpress/Blazor#86]
I found two possible bugs while using `MultipleSelectedDataRows` function in the grid.

1. Every time I click on a row in the grid, the `MultipleSelectedDataRowsChanged` function is called twice. The first time with an empty dataset, the second time containing data.
2. When I select `row1` on the first page, switch to the second page and select `row2`, the `MultipleSelectedDataRowsChanged` returns both elements `row1` and `row2`, instead of only the current element of the current page, `row2`.

I'm not sure if these bugs only occur in combination with the new remote data function. So I added a example solution: [BlazorApp1.zip](https://github.com/DevExpress/Blazor/files/4097234/BlazorApp1.zip)

**Comment by zabelin-vladimir** [comment]
Hello @rysep2

Thank you for your project. I reproduced the behavior described in the first point. We will research it in the context of the [DataGrid for Blazor - The MultipleSelectedDataRowsChanged event fires two times when a row is selected](https://supportcenter.devexpress.com/ticket/details/t854358/datagrid-for-blazor-the-multipleselecteddatarowschanged-event-fires-two-times-when-a-row) ticket.

Regarding the second point, it's expected behavior. The same behavior can be reproduced with our ASP.NET WebFroms GridView. Please open the [Using Row Clicks](https://demos.devexpress.com/ASPxGridViewDemos/Selection/SelectByRowClick.aspx) demo, select several rows on the first page (with the Ctrl key), go to the second page, select a row, and return back to the first page. The previously selected rows on the first page are still selected. Would you please clarify if this behavior is not expected to you? How our grid should operate in this case?

**Comment by rysep2** [comment]
> Regarding the second point, it's expected behavior. The same behavior can be reproduced with our ASP.NET WebFroms GridView. Please open the Using Row Clicks demo, select several rows on the first page (with the Ctrl key), go to the second page, select a row, and return back to the first page. The previously selected rows on the first page are still selected. Would you please clarify if this behavior is not expected to you? How our grid should operate in this case?

Ok, I expected that if I select a row on the first page and then switch to the second page I can either..
- ..select a row and then get only this row back
- ..select a row (with Ctrl key) and get both rows back

I would be ok with the behaviour you described but it doesn't work like this in the project I sent you. When I select a row and switch pages, the same row isn't selected anymore in the GUI when I return to the first page.

**Comment by zabelin-vladimir** [comment]
Hello @rysep2,

> When I select a row and switch pages, the same row isn't selected anymore in the GUI when I return to the first page.

It's necessary to specify the [KeyFieldName](https://docs.devexpress.com/Blazor/DevExpress.Blazor.Base.DxDataGridBase-1.KeyFieldName) property to avoid this issue. Please check this approach and let me know if it helps.

**Comment by rysep2** [comment]
Hi @zabelin-vladimir 

> It's necessary to specify the KeyFieldName property to avoid this issue. Please check this approach and let me know if it helps.

This worked, thanks!

Now I went a step further and tried to combine those features with virtual scrolling. I only see the first page and can't scroll any further. Any idea what the problem is here?

I'm sorry for all the questions! I've got a lot of requirements for my grid..

I updated my sample projecte here: [BlazorApp1_VirtScroll.zip](https://github.com/DevExpress/Blazor/files/4102018/BlazorApp1_VirtScroll.zip)

**Comment by zabelin-vladimir** [comment]
Hello @rysep2 

I reproduced the same issue with our demos locally and created the [DataGrid for Blazor - Virtual scrolling doesn't work if the grid is bound using the CustomData property](https://supportcenter.devexpress.com/ticket/details/t854655/datagrid-for-blazor-virtual-scrolling-doesn-t-work-if-the-grid-is-bound-using-the) ticket in our support center to process it.

**Comment by zabelin-vladimir** [comment]
Hello @rysep2,

I would like to note that both of the mentioned issues were fixed, the first one in the 19.2.3 version, the second one in the 19.2.4 version, I have checked both with the latest "19.2.4-preview" NuGet package.
