### ISSUE TITLE
How to create a collapsible panel (accordion) based on CheckBox components in a switch type which are bound to enum

### ISSUE THREAD

**Issue by hybrid2102** [DevExpress/Blazor#97]
I have an _EditForm_ binded with a _Model_ called **Car**.
Inside the form I placed three _DxCheckBoxes_, binded with the three values of **Car.MeasurementTool** enum (**HaStaff**, **HaProp**, **Cdb**).
Every _DxCheckBox_ should show/hide it's related card-body, but the card-body shows only when I click the _DxButton_ to submit the form.
Is it possible to achieve what I want?

```
<EditForm Model="@Car" OnValidSubmit="@HandleValidSubmit" OnInvalidSubmit="@HandleInvalidSubmit">

    <div class="card">
        <div class="card-header">
            <DxCheckBox CheckType="CheckType.Switch" @bind-Checked="@Car.MeasurementTool" ValueChecked="@MeasurementTool.HaStaff">Official Kit</DxCheckBox>
        </div>
        @if (@Car.MeasurementTool == MeasurementTool.HaStaff)
        {
            <div class="card-body"><h5>Official Kit operations:</h5><!-- ... --></div>
        }
    </div>

    <div class="card">
        <div class="card-header">
            <DxCheckBox CheckType="CheckType.Switch" @bind-Checked="@Car.MeasurementTool" ValueChecked="@MeasurementTool.HaProp">Personal Kit</DxCheckBox>
        </div>
        @if (@Car.MeasurementTool == MeasurementTool.HaProp)
        {
            <div class="card-body"><h5>Personal Kit operations:</h5><!-- ... --></div>
        }
    </div>

    <div class="card">
        <div class="card-header">
            <DxCheckBox CheckType="CheckType.Switch" @bind-Checked="@Car.MeasurementTool" ValueChecked="@MeasurementTool.Cdb">CDB</DxCheckBox>
        </div>
        @if (@Car.MeasurementTool == MeasurementTool.Cdb)
        {
            <div class="card-body"><h5>CDB operations:</h5><!-- ... --></div>
        }
    </div>

    <DxButton RenderStyle="ButtonRenderStyle.Primary" Text="Save" SubmitFormOnClick="true" />

</EditForm>
```

**Comment by outsidergiant** [comment]
Hi,

Thank you for contacting us. For this, instead of the two-way binding, you need to specify the **CheckedExpresion** property and handle the [CheckedChanged](https://docs.devexpress.com/Blazor/DevExpress.Blazor.Base.DxCheckBoxBase-1.CheckedChanged) event to update your Car's MeasurementTool and the changed state:
`
public void OnCheckedChanged(MeasurementTool value) {
    Car.MeasurementTool = value;
    InvokeAsync(StateHasChanged);
}
`
I've attached a sample project and recorded a video to demonstrate how it works. 
[Issue97.zip](https://github.com/DevExpress/Blazor/files/4256967/Issue97.zip)

[Video.zip](https://github.com/DevExpress/Blazor/files/4256946/Video.zip)
